### ISSUE TITLE
Host site on github pages at mentalhues.github.io

### ISSUE THREAD

**Issue by KirstieJane** [mentalhues/mentalhues.github.io#14]
If you create a github organisation called `mentalhues` you can host a static website: mentalhues.github.io.

Here are the step by step instructions if you want to go down this route:

1. Get an academic github discount (otherwise you have to pay for organisations I think): https://education.github.com
2. Create an organisation called `mentalhues`. I don't know if it exists yet, but hopefully it doesn't! https://help.github.com/articles/creating-a-new-organization-from-scratch
3. Transfer ownership of this organisation to `mentalhues`: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/
4. Rename the repository `mentalhues.github.io` (so it'll be at `github.com/mentalhues/mentalhues.github.io`)
5. Switch on the github pages hosting in settings: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

You can host the website from a `gh-pages` branch, or from the `master` branch or from a `docs` folder. I personally think just hosting from `master` makes most sense, but it's totally up to you!

Here's a guide to get you started (although I don't think it really tells you all that much): https://pages.github.com/.

Here's an example hosted by jekyll that might work well for **mentalhues**: https://github.com/TeamCalALC/TeamCalALC.github.io which is based on https://github.com/BlackrockDigital/startbootstrap-freelancer.

I hope this is helpful! Happy to discuss ✨✨✨✨

**Comment by erindcole** [comment]
Thank you Kirstie! This information is very helpful. I'll comment here or ping you directly if I run into any challenges with setting this up.

**Comment by erindcole** [comment]
I'm wondering about step #4 on your comment. With what will renaming my organization like that help? I'm curious about this, don't completely understand.

**Comment by Islast** [comment]
github pages offers to host a website for you at *username*.github.io. To do this the associated repository must be called *username*.github.io, more info here: https://pages.github.com/

Alternatively you can use github to build the project at a url you own https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/, I don'tknowin this case if the usual rulesabout repository naming still apply

**Comment by KirstieJane** [comment]
Thanks @Islast - yep - if you don't re-name the repo it will be hosted at `https://mentalhues.github.io/mentalhues` whereas if you do re-name the repo (to `mentalhues.github.io`) the website will be found at `https://mentalhues.github.io`.

**Comment by KirstieJane** [comment]
Hey @erindcole - here's the example I found to integrate flask with github pages https://github.com/sloria/flask-ghpages-example

**Comment by erindcole** [comment]
@KirstieJane could you or @Islast check my rename for the repo? Also, checking out the integration with flask now...

**Comment by KirstieJane** [comment]
Yep! I can see the page at mentalhues.github.io! Way to go!! ✨ 💯 👾 

I think this issue can be closed 😸
