### ISSUE TITLE
Make talk for California Women in Computing Conference

### ISSUE THREAD

**Issue by KirstieJane** [mentalhues/mentalhues.github.io#15]
Talk date: 15th April 2018
Length: 12 mins, with 3 mins discussion

Three chapters:

1. Describe Mental Hues - the problem statement - why we need it
2. Describe open leadership training
3. Personal experience of building in the open - scary in theory but not in practise

Stretch goal - highlight the inclusive development *by* people w mental health disorders *for* people with mental health disorders.

**Take home message**: Harnessing and growing an idea on the open internet is fun and empowering.

Not mentioned in talk (because short time): Where Mental Hues is going and how people can help!

Some useful resources:

* Kirstie's talk on culture change at CW18: https://doi.org/10.6084/m9.figshare.6025652
* Abby's talk on

**Comment by erindcole** [comment]
@KirstieJane I updated your comment with the talking and discussion lengths. Looks like I can squeeze the stretch goal 🎆

**Comment by KirstieJane** [comment]
That’s great!! :tada:

Here are the resources I didn’t finish entering yesterday (doh!):

Copied from an email from @acabunoc:

> MoFo - Fueling the movement slides:
https://docs.google.com/presentation/d/1boHHtcOtklSaa7lCbuy8wwDPlhb6CaivkMKXRO2fmOc/edit
> 
>My slides from week 0 (parts are taken from the deck above):
https://docs.google.com/presentation/d/1EDlws1Ai7vmEK-xBFILUemy5nbIhrKV6gtQcaXw6TJM/edit#slide=id.g254663fe2f_0_78

**Comment by erindcole** [comment]
Thanks!!

My slides so far:
https://docs.google.com/presentation/d/1ibYwpm5LeZsACDC4NLvya-gwerCZ_BplFOwH5CepM9M/edit?usp=sharing

**Comment by KirstieJane** [comment]
Slides are awesome! I love the talk so much 😍 😻 💖 

Do you want to maybe embed them in the README? Or start a new file in the repo called `presentation-resources.md` which could contain lists of talks you give? (I think this will be the first of many!)
