### ISSUE TITLE
Record video of talk describing the creation of mental hues

### ISSUE THREAD

**Issue by KirstieJane** [mentalhues/mentalhues.github.io#19]
I love the talk that @erindcole made for California Women in Computing conference (see #15) so much that I wonder if it would be possible to make a recording of the presentation.

Here's a [tip sheet](https://docs.google.com/document/d/1_buuJOoh3Bbag0V1oRx4iBA1VkjKN4axrghkFERAaus/edit#) that I created based on an original guide by Zannah at Mozilla on how to record a video lecture (so with slides etc) using [OBS Studio](https://obsproject.com).

Two options are:
* A shot of Erin saying hello and thank you at the beginning and end and then a voice over over the slides for the rest of the talk
* A split screen with the slides and Erin's head while she's speaking for all of the talks.

I don't really have a strong opinion - I think option 1 is easier but 2 might be more engaging because we'd get to see more of the speaker?

The recording could be hosted on youtube and then embedded in the https://mentalhues.github.io website.

**Comment by erindcole** [comment]
I am getting to work on this, and am looking into the tools tonight. @KirstieJane I'd like to dedicate the talk to you. As soon as I record it, I will send it your way, and include it in the new file I made according to the comment in Issue #15

**Comment by erindcole** [comment]
I recorded my presentation a while back, but have been hesitant to share it publicly. This destigmatization mission is a personal challenge. That said, I do want to share it publicly now. @KirstieJane I sent you the video. What do you think? How should we publish it?

**Comment by KirstieJane** [comment]
Wooo - sorry I didn't reply @erindcole!! You. Rock.

Did you send me the video recently, or is it the same one from a while ago?

There are a few options for sharing it with others. The easiest would be to upload it to YouTube and then link to it from either the README or the presentations file (introduced in #22).

Does that make you anxious though? Would you prefer it to be hosted somewhere more private than YouTube? I think you can set the YouTube privacy to not show up in searches so it can only be found if you already have the link.

But, to be clear, whatever **you** feel comfortable is what we'll do. It was SUCH a brave talk. Just doing it was amazing, you don't *have* to do anything more. ❤️ 💕 💓

**Comment by erindcole** [comment]
I uploaded the video. You can find it here: https://youtu.be/9Siia0bhuJc
