### ISSUE TITLE
Clarifying how users interact with a Hue

### ISSUE THREAD

**Issue by asg017** [mentalhues/mentalhues.github.io#25]
I just want to clarify a few things about what MentalHues will be before planning anything out!

1. Will a user be able to define their own hue, or will they have to choose from a pre-selected set of hues?

2. Can one hue be associated with multiple mental health topics? For example, if someone already wrote a Hue about their depression and used the color light blue, could someone else use that light blue color for a different hue about a different topic, or would light blue forever be associated with depression?

3. Should Hues be approved before they are posted? This could avoid issues like spam, accidentally including personal identifying information, posts that don't follow the Code of Conduct, etc. This would require some more engineering work to make it happen (who decides if a post is approved, what do we do with dis-approved post, etc.), but I think it's something that could be beneficial. I could create another issue about this if it's something other people would like to work on!

**Comment by erindcole** [comment]
Hi @asg017 .  Apologies for not responding to this issue you created earlier. I haven't been feeling great, but am getting better. I've been focusing on my health and other priorities. 

Could you revisit the Contributing Guidelines? It seems you created this issue differently than the Contributing Guidelines outline. They state that we work according to issues that already exist. If while working on an issue, the contributors decide to branch an idea to another issue, then a new issue is created. There must be a reference in the new issue to the issue from which it branched. Does this make sense? The Contributing Guidelines explain this in a step by step way. Thanks.
