### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by erindcole** [mentalhues/mentalhues.github.io#6]
I am currently drafting the README file, and would like to ask for suggestions and ideas. What needs to be included in this README so that people wanting to join the community can have a clear idea of this project?

**Comment by brennacole** [comment]
I would suggest talking to a therapist/expert in the field for a list of resources.

**Comment by erindcole** [comment]
I contacted [Active Minds, UC San Diego chapter](http://activemindsucsd.wixsite.com/am-ucsd), about some resources to include in the README. @KirstieJane what do you think of the doc below? I'm thinking to include a couple warm lines, or at least an explanation of how to reach out to professionals in case someone gets triggered/has a strong response to the content of the repo or site.

https://docs.google.com/document/d/1d_EQjwRnIzPThKtHm1r60YxGjdhiNqu4zYV12LzMxuk/edit?usp=sharing

**Comment by Islast** [comment]
I was looking for an international helpline directory and I found [this](http://togetherweare-strong.tumblr.com/helpline) unfortunately the entries for many countries aren't detailed. They also have a [list of chatrooms ordered by subject](http://togetherweare-strong.tumblr.com/chat). This isn't a very polished resource, but I couldn't find anything more comprehensive.

**Comment by erindcole** [comment]
For now, the README is solid.

**Comment by erindcole** [comment]
I have realized something about the README for this project. It includes some experiences that are personal to me. Please email me directly at erincole567@gmail.com if there is anything about this project that you would like to discuss and you need changes made and you want to remain anonymous. I will treat all direct correspondence with me as confidential. I am not a health care professional, so please do realize this before you contact me.
