### ISSUE TITLE
Google Form Used to Provide Initial Community Thoughts 

### ISSUE THREAD

**Issue by erindcole** [mentalhues/mentalhues.github.io#8]
Below is a link to a Google form, which you can use describe ideas, views, and thoughts about mental health disorders. Please answer any or all questions you like, and provide any other thoughts you would like to share with me. I treat all responses to this form as confidential.

https://goo.gl/forms/mzFkPQ1105kEmGrv1

**Comment by Islast** [comment]
@erindcole is this something you'd like to be widely shared?

**Comment by bladex1200** [comment]
Likewise, would it be okay if we shared this in FB friend groups or on our social media to try and get more feedback?

**Comment by erindcole** [comment]
@Islast and @bladex1200 , yes please!

**Comment by erindcole** [comment]
I believe I have gathered initial thoughts. If you would like to describe more thoughts about the direction of the project, please email me directly at erincole567@gmail.com.
